apiVersion: skaffold/v2alpha3
kind: Config
deploy:
 kubectl:
  manifests:
   - ./infra/k8s/*
build:
#  googleCloudBuild:
#   projectId: ticketing-dev-288901
 local:
  push: false
 artifacts:
  - image: shrestharavee1/auth
    context: auth
    docker:
     dockerfile: Dockerfile
    sync:
     manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: shrestharavee1/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.js'
        dest: . 